import { http, createConfig } from "wagmi";
import {
  mainnet,
  optimism,
  arbitrum,
  base,
  polygon,
  bsc,
  avalanche,
  mantle,
  linea,
  scroll,
  blast,
  mode,
  gnosis,
  metis,
  manta,
  fantom,
} from "wagmi/chains";
import { injected } from "wagmi/connectors";

export const config = createConfig({
  chains: [
    mainnet,
    optimism,
    arbitrum,
    base,
    polygon,
    bsc,
    avalanche,
    mantle,
    linea,
    scroll,
    blast,
    mode,
    gnosis,
    metis,
    manta,
    fantom,
  ],
  connectors: [injected()],
  transports: {
    [mainnet.id]: http(),
    [optimism.id]: http(),
    [arbitrum.id]: http(),
    [base.id]: http(),
    [polygon.id]: http(),
    [bsc.id]: http(),
    [avalanche.id]: http(),
    [mantle.id]: http(),
    [linea.id]: http(),
    [scroll.id]: http(),
    [blast.id]: http(),
    [mode.id]: http(),
    [gnosis.id]: http(),
    [metis.id]: http(),
    [manta.id]: http(),
    [fantom.id]: http(),
  },
});
